### ISSUE TITLE
on driver page there is a very small empty box below the nav bar

### ISSUE THREAD

**Issue by MargieTangOxley** [reed-college/nightbus#81]

**Comment by p-j-graham** [comment]
This is the box that contains the "status update" warning. It spawns on the page when it loads, and disappears only after one of the buttons has been pressed. 

This box might be redundant, as there is already a pop-up box that alerts the driver the status has been updated.

**Comment by MargieTangOxley** [comment]
I made a pull request that should fix this problem.
